new 사무직 페이지 구현하기
f-lab-edu/kozolTime pull request #11
Opened 2022-11-09 10:29 UTC by hifrogie

제가 구현 했던 최신 내용들이 없는 브랜치라서 그 내용이 있는 mainActivity를 체리픽 해와도 될까요?
그리고 제가 풀리퀘 3에서 고쳤던 내용들이 포함이 안되어있네요 ㅜㅜ  
고쳤던 내용은 다른 줄기에 있는 모양이에요 이를 어쩌죠 ㅜㅜ

2022-11-09 13:32 UTC, dktfr commented
@hifrogie 
지금 겪고있는 상황은 여러개발자와 동시에 작업할 때, 자주 겪는 상황입니다.
내가 작업하는 브랜치에, 다른 개발자가 작업했던 내용이 없는 상황인거죠.
이럴때는 rebase를 보통 이용해서 브랜치를 정리해줍니다.

[이전 PR](https://github.com/f-lab-edu/kozolTime/pull/6)에서 고쳤던 내용들은 develop에 반영이 되어있으니,
현재 브랜치(feature/office_job2)에서 develop을 rebase해주면 내용을 가져올 수 있습니다.
* feature/office_job2 로 check-out
* branches -> develop -> `rebase currunt onto selected`
* Push -> Force Push
의 순서로 하면 feature/office_job2가 develop의 최신 내용을 받아올 수 있게 됩니다.

(다만... 코드가 충돌이 될 수도 있어요.. 그때는 두 브랜치의 수정사항을 비교해서 바꿔주어야 합니다.)

2022-11-11 08:38 UTC, hifrogie commented
실수로 풀을 해버렸네요 다시 오픈 합니다.

2022-11-11 15:27 UTC, dktfr requested changes
내용 확인해주세요~

2022-11-11 15:27 UTC, dktfr commented on frog/src/main/java/kr/co/ky/kozoltime/NewOffice.kt
> +class NewOffice : Fragment() {
Fragment, Activity 등의 컴포넌트 이름은, 관례적으로 해당 클래스로 끝나는게 좋습니다.
(ex. NewOfficeFragment)

2022-11-11 15:27 UTC, dktfr commented on frog/src/main/java/kr/co/ky/kozoltime/NewOffice.kt
> +private const val ARG_PARAM2 = "param2"
PARAM1, PARMA2보다는 해당 Param이 어떤 값인지 이름을 명확하게 해주면 코드 가독성이 좋습니다.

2022-11-11 15:27 UTC, dktfr commented on frog/src/main/java/kr/co/ky/kozoltime/OfficeAdapter.kt
> +   var postList:ArrayList<Post> = arrayListOf()
타입을 선언할때는 가급적 인터페이스 타입으로 선언하면 좋습니다.

2022-11-11 15:27 UTC, dktfr commented on frog/src/main/java/kr/co/ky/kozoltime/OfficeAdapter.kt
> +        firestore?.collection("kozoltime")?.addSnapshotListener{querySnapshot,firebaseFirestoreException -> postList.clear()
`FirebaseFirestore.getInstance()`함수가 Nullable 반환인가요??

2022-11-11 15:27 UTC, dktfr commented on frog/src/main/java/kr/co/ky/kozoltime/OfficeAdapter.kt
> +        if(postList != null) {
엘비스 연산자 (`?:`)로 바꿔서 표기해보세요. (코틀린 책 6장)

2022-11-11 15:27 UTC, dktfr commented on frog/src/main/java/kr/co/ky/kozoltime/Post.kt
> +    constructor(): this("개구리","개구리","개구리")
이건 테스트용 생성자인가요??

2022-11-12 13:13 UTC, hifrogie commented on frog/src/main/java/kr/co/ky/kozoltime/NewOffice.kt
> +class NewOffice : Fragment() {
넵!

2022-11-12 13:14 UTC, hifrogie commented on frog/src/main/java/kr/co/ky/kozoltime/NewOffice.kt
> +private const val ARG_PARAM2 = "param2"
네 이름을 명확히 하겠습니다.

2022-11-12 13:15 UTC, hifrogie commented on frog/src/main/java/kr/co/ky/kozoltime/NewOffice.kt
> +private const val ARG_PARAM2 = "param2"
아직 그 클래스는 손은 대지 않은 상태라서 손 댈 때 고칠게요 아직 구상하고 있어요

2022-11-12 13:18 UTC, hifrogie commented on frog/src/main/java/kr/co/ky/kozoltime/OfficeAdapter.kt
> +   var postList:ArrayList<Post> = arrayListOf()
postList에 ArrayList를 말씀하시는 건가요?
인터페이스 타입으로 선언하는 것이 무엇인지 모르겠어요

2022-11-12 13:22 UTC, hifrogie commented on frog/src/main/java/kr/co/ky/kozoltime/OfficeAdapter.kt
> +        firestore?.collection("kozoltime")?.addSnapshotListener{querySnapshot,firebaseFirestoreException -> postList.clear()
아니요 
뒤에 있는 안전한 호출 연산자 지웠어요!

2022-11-12 13:25 UTC, hifrogie commented on frog/src/main/java/kr/co/ky/kozoltime/OfficeAdapter.kt
> +        if(postList != null) {
넵 엘비스 연산자에 도달할 일이 없다고 문구를 주네요

2022-11-12 13:25 UTC, hifrogie commented on frog/src/main/java/kr/co/ky/kozoltime/Post.kt
> +    constructor(): this("개구리","개구리","개구리")
그게 없으면 정보를 받을 수 가 없어서 만들었어요

2022-11-12 14:02 UTC, dktfr commented on frog/src/main/java/kr/co/ky/kozoltime/OfficeAdapter.kt
> +   var postList:ArrayList<Post> = arrayListOf()
네 ArrayList를 의미한거 맞습니다.
postList의 타입을 ArrayList로 선언하게되면, 그 `타입만` 가능한데,
만약 postList의 타입이 List라면 ArrayList이든, LinkedList이든 필요에 맞게 바꿔줄수 있곘죠??

2022-11-12 14:05 UTC, dktfr commented on frog/src/main/java/kr/co/ky/kozoltime/Post.kt
> +    constructor(): this("개구리","개구리","개구리")
정보를 받을수가 없다는게 무슨 의미일까요??
Post 클래스에 기본생성자(인자 필요없는 생성자)가 필요하다는 걸까요??

만약 그 의미라면, 디폴트 파라미터로 처리하도록 바꾸는게 코드가 더 깔끔해지고, 불필요한 값으로 초기화되는것도 방지할 수 있을것 같네요

2022-11-12 14:08 UTC, dktfr requested changes
리뷰 완료했습니다.
추가 코멘트 확인해주세요.

2022-11-12 14:08 UTC, dktfr commented on frog/src/main/java/kr/co/ky/kozoltime/OfficeAdapter.kt
> +            return postList.size ?: return 0
postList에도 `?` 연산자를 이용하면 if문도 제거할 수 있습니다.
그리고, 엘비스연산자 뒤에 return은 중복된 키워드네요~
스튜디오에서 경고 띄워줄텐데, 유심히 보고 시키는대로 따라하면 코드스타일을 개선하는데 많은 도움이 됩니다.

2022-11-15 05:19 UTC, hifrogie commented on frog/src/main/java/kr/co/ky/kozoltime/OfficeAdapter.kt
> +   var postList:ArrayList<Post> = arrayListOf()
아 무슨 뜻인지 이해했습니다.

2022-11-15 11:43 UTC, hifrogie commented on frog/src/main/java/kr/co/ky/kozoltime/OfficeAdapter.kt
> +   var postList:ArrayList<Post> = arrayListOf()
mutableList로 바꿔봤어요

2022-11-15 13:22 UTC, hifrogie commented on frog/src/main/java/kr/co/ky/kozoltime/Post.kt
> +    constructor(): this("개구리","개구리","개구리")
네 디폴트 파라미터로 바꿨어요

2022-11-15 13:23 UTC, hifrogie commented on frog/src/main/java/kr/co/ky/kozoltime/OfficeAdapter.kt
> +            return postList.size ?: return 0
넵 !! 고쳤어요

2022-11-15 14:55 UTC, dktfr approved these changes

2022-11-16 03:13 UTC, merged