글 쓰는 부분
f-lab-edu/kozolTime pull request #12
Opened 2022-11-16 03:50 UTC by hifrogie

글 써서 파이어베이스에 올리고 올린 글 뷰에 올리는 것
일단은 gitignore만 했습니다.

2022-11-17 14:32 UTC, dktfr requested changes

2022-11-17 14:32 UTC, dktfr commented on frog/src/main/java/kr/co/ky/kozoltime/WriteActivity.kt
> +    var fbFirestore = FirebaseFirestore.getInstance()
fbAuth, fbFirestore는 한번 초기화된 이후에 다시 초기화할 일이 없기때문에,
var보다는 val이 좋겠습니다. 변경가능한 가능성을 최소화하도록 코드 작성하는걸 습관들여주세요.

2022-11-17 14:32 UTC, dktfr commented on frog/src/main/java/kr/co/ky/kozoltime/WriteActivity.kt
> +        write_spinner.prompt="직종을 선택해주세요."
문자열리소스 사용해주세요

2022-11-17 14:32 UTC, dktfr commented on frog/src/main/java/kr/co/ky/kozoltime/WriteActivity.kt
> +            postInfo.context = write_ssul_context.text.toString()
postInfo 객체에 주입 후에 wirteData에 다시 넣는 대신, 바로 writeData에 넣으면 되지 않았을까요??
왜 굳이 중간에 postInfo 객체에 주입했는지 궁금합니다.

2022-11-18 04:03 UTC, hifrogie commented on frog/src/main/java/kr/co/ky/kozoltime/WriteActivity.kt
> +    var fbFirestore = FirebaseFirestore.getInstance()
넵 바꿨습니다.

2022-11-18 04:11 UTC, hifrogie commented on frog/src/main/java/kr/co/ky/kozoltime/WriteActivity.kt
> +        write_spinner.prompt="직종을 선택해주세요."
사용했습니다!!

2022-11-18 04:13 UTC, hifrogie commented on frog/src/main/java/kr/co/ky/kozoltime/WriteActivity.kt
> +            postInfo.context = write_ssul_context.text.toString()
두 개의 블로그 글을 보고 합치다 보니 굳이 두개로 나눠버렸네요.
코드 오스트랄로피테쿠스의 길은 멀고도 험하네요.
담에는 기능만 구현할 게 아니라 효율적인 코드를 만드려고 노력하겠습니다.

2022-11-20 12:10 UTC, dktfr approved these changes

2022-11-21 04:57 UTC, merged