커뮤니티 창 글쓰기 구현
f-lab-edu/kozolTime pull request #15
Opened 2022-11-16 12:14 UTC by hifrogie

좋아요 기능은 나중에 구현하려구요

2022-11-17 14:42 UTC, dktfr requested changes

2022-11-17 14:42 UTC, dktfr commented on frog/src/main/java/kr/co/ky/kozoltime/CommunityAdapter.kt
> +            for(snapshot in querySnapshot!!.documents){
`!!`는 NotNull이라는 확신이 있을때에만 사용하는게 좋은데, querySanpshot이 null일 가능성이 없나요??

2022-11-17 14:42 UTC, dktfr commented on frog/src/main/java/kr/co/ky/kozoltime/CommunityWriteActivity.kt
> +class CommunityWriteActivity : AppCompatActivity() {
동일한 코드를 복붙한것으로 보여서 같은 내용인데, #12에서 WriteActivity에 리뷰한 내용과 같습니다.

2022-11-17 14:42 UTC, dktfr commented on frog/src/main/java/navigation/CommunityFragment.kt
> +        community_rv.layoutManager = LinearLayoutManager(getActivity())
onStart()에서 adapter, layoutManager를 초기화하는 이유가 있을까요??
onStart()는 홈버튼을 눌렀다가 다시 앱진입했을때에도 발생할 수 있는 콜백메서드이기 떄문에, 매번 CommunityAdapter(), LinearLayoutManager() 인스턴스가 생성될 것 같은데요.

`onViewCreated()`라는 콜백이 어울리는 초기화시점일 것 같습니다. 해당 콜백을 찾아서 설명을 읽어보세요.

2022-11-18 05:00 UTC, hifrogie commented on frog/src/main/java/kr/co/ky/kozoltime/CommunityAdapter.kt
> +            for(snapshot in querySnapshot!!.documents){
null일 가능 성이 있어서 if 문을 추가해봤어요

2022-11-18 05:01 UTC, hifrogie commented on frog/src/main/java/kr/co/ky/kozoltime/CommunityWriteActivity.kt
> +class CommunityWriteActivity : AppCompatActivity() {
넵 똑같이 고치겠습니다.

2022-11-18 05:08 UTC, hifrogie commented on frog/src/main/java/navigation/CommunityFragment.kt
> +        community_rv.layoutManager = LinearLayoutManager(getActivity())
읽었습니다! 초기화 단계의 코드는 onStart에 쓰는 것 보다 onViewCreated()에 쓰는 것이 좋다고 나와있네요!
바꿨습니다.

2022-11-20 12:11 UTC, dktfr approved these changes

2022-11-21 05:32 UTC, merged