마이 페이지를 만들었어요
f-lab-edu/kozolTime pull request #16
Opened 2022-11-17 13:25 UTC by hifrogie

프레임 안은 아직 구현 안했어요!
닉네임을 바꾸면 닉네임 텍스트 뷰가 바뀌어야하는데 안바뀌네요 ㅜㅜ

2022-11-17 14:55 UTC, dktfr requested changes
NickNameActivity는 어디서 호출이 되는걸까요?
DetailViewFragment() 내에서 NickNameActivity로 이동하는 클릭이벤트가 있기는 한데...
DetailViewFragment()는 NickNameActivity내에서 표시되는 프레그먼트로 보여서요. (현재는 주석으로 막은것처럼 보입니다만)

2022-11-17 14:55 UTC, dktfr commented on frog/src/main/java/kr/co/ky/kozoltime/NickNameActivity.kt
> +class NickNameActivity : AppCompatActivity() {
#12에서 WriteActivity에 했던 리뷰와 동일합니다.

2022-11-17 14:55 UTC, dktfr commented on frog/src/main/java/kr/co/ky/kozoltime/NickNameActivity.kt
> +class NickNameActivity : AppCompatActivity() {
추가로, NickNameActivity는 어디서 호출이 되는건가요?

2022-11-18 05:14 UTC, hifrogie commented
아 그건 프레그먼트에서 액티비티로 화면전환을 하려다가 실패한 코드에요! 디테일 프래그먼트에서 버튼을 누르면 액티비티로 변환 되는 것이고 디테일 프래그먼트는 원래 메인액티비티에서 펼쳐지는 프래그 먼트에요 디테일 프래그먼트가 닉네임 액티비티에 속해 보이는 거는 제가 잘못 작성한거에요

2022-11-18 05:15 UTC, hifrogie commented on frog/src/main/java/kr/co/ky/kozoltime/NickNameActivity.kt
> +class NickNameActivity : AppCompatActivity() {
넵
고쳤습니다.

2022-11-18 13:56 UTC, hifrogie commented
닉네임 중복 제거와 닉네임 설정을 만들어 봤어요 ㅜㅜ 근데 잘 안되네요 ㅜㅜ 그래도 열심히 해보겠습니다.

2022-11-20 12:12 UTC, dktfr approved these changes

2022-11-21 05:38 UTC, merged