콜백함수를 사용해서 어댑터와 데이터 호출 을 분리
f-lab-edu/kozolTime pull request #18
Opened 2022-11-25 11:34 UTC by hifrogie

콜백함수

2022-11-29 12:25 UTC, dktfr requested changes

2022-11-29 12:25 UTC, dktfr commented on frog/src/main/java/data/FirebaseData.kt
> +    fun communityFirebase(path: String, finishedCallback: TimeCallback) {
메서드가  `어떤 동작`을 하는지를 명시하기 위한 목적으로, 메서드 이름은 동사로 시작하는 것이 관례입니다.

2022-11-29 12:25 UTC, dktfr commented on frog/src/main/java/data/FirebaseData.kt
> +    }
들여쓰기가 들쭉날쭉하여 가독성이 좋지 않습니다.
다른 개발자와 같이 작업하는 프로젝트라면 혼자 코드를 작성하는 것이 아니기때문에,
코드를 깔끔하게 짜서 읽기 수월하도록 해야 합니다.

2022-11-29 12:25 UTC, dktfr commented on frog/src/main/java/kr/co/ky/kozoltime/WriteActivity.kt
> +            val kozoltime = "kozoltime"
굳이 임시변수로 뺀 이유는 무엇인가요??
그리고 변수이름은 그 변수가 어떤 값을 가지고 있는지 알도록 지어야합니다.
다른 개발자가 `kozoltime`이라는 변수이름을 보면 어떤 값이 들어있다고 생각할수 있을까요?

2022-11-29 12:25 UTC, dktfr commented on frog/src/main/java/kr/co/ky/office/OfficeActivity.kt
> +                office_rv.layoutManager = LinearLayoutManager(this@OfficeActivity)
LayoutManager와 Adapter를 초기화하는 로직이 adapter에 들어있는 이유는 무엇인가요?
지난주에 삽질하셨던 내용과 동일합니다. 이부분도 특별한 이유가 없다면 View가 초기화하는 시점으로 옮겨주세요.

2022-11-29 12:25 UTC, dktfr commented on frog/src/main/java/kr/co/ky/office/OfficeActivity.kt
> +                officeAdapter = CommunityAdapter(mutableList)
CommunityAdapter() 각각 생성되고 있는데, 이부분 수정해주세요.

2022-11-29 12:25 UTC, dktfr commented on frog/src/main/java/navigation/CommunityFragment.kt
> +                community_rv.layoutManager = LinearLayoutManager(activity)
OfficeActivity의 리뷰와 동일합니다. LayoutManager, Adapter의 초기화코드는 뷰 초기화시점에 해주세요.

2022-11-30 09:55 UTC, hifrogie commented on frog/src/main/java/data/FirebaseData.kt
> +    fun communityFirebase(path: String, finishedCallback: TimeCallback) {
수정했습니다.

2022-11-30 09:58 UTC, hifrogie commented on frog/src/main/java/data/FirebaseData.kt
> +    }
수정했습니다.

2022-11-30 10:00 UTC, hifrogie commented on frog/src/main/java/kr/co/ky/kozoltime/WriteActivity.kt
> +            val kozoltime = "kozoltime"
""안의 스트링이 바뀌어도 빠르게 고치고 싶어서 임시변수에 담았어요
변수이름은 바꿀게요

2022-11-30 10:02 UTC, hifrogie commented on frog/src/main/java/kr/co/ky/office/OfficeActivity.kt
> +                office_rv.layoutManager = LinearLayoutManager(this@OfficeActivity)
adapter를 초기화 하는 로직에 adapter에서 받아오는 리스트가 꼭 필요해서 그렇게 넣었어요
layooutmanager는 밖으로 뻈어요

2022-11-30 10:04 UTC, hifrogie commented on frog/src/main/java/navigation/CommunityFragment.kt
> +                community_rv.layoutManager = LinearLayoutManager(activity)
layoutmanager를 밖으로 뻈어요

2022-11-30 10:39 UTC, hifrogie commented on frog/src/main/java/kr/co/ky/office/OfficeActivity.kt
> +                officeAdapter = CommunityAdapter(mutableList)
수정했어요

2022-11-30 13:06 UTC, dktfr approved these changes
수고하셨습니다

2022-11-30 13:18 UTC, merged