이미지를 파이어 베이스에서 불러오려고 했어요.
f-lab-edu/kozolTime pull request #20
Opened 2022-12-02 10:59 UTC by hifrogie

그런데 파이어베이스 imageuri를 못 불러오고 있어요 저장은 되는데 제 앱에 불러와지지 않네요 ㅜㅜ 에러 메세지도 안떠서 잘 모르겠어요~ 일단 커밋 했어요 내일 다시 볼게요

2022-12-03 09:01 UTC, dktfr requested changes
파이어페이스 문서상으로는 getXXX() 하는 메서드를 지원하는데,
그부분을 쓰는 코드가 보이지 않네요.

https://firebase.google.com/docs/storage/android/download-files

요 문서 참고해보세요.

2022-12-03 09:01 UTC, dktfr commented on frog/src/main/java/kr/co/ky/community/CommunityWriteActivity.kt
> +            val fileName = "${SimpleDateFormat("yyyymmdd_HHmm").format(Date())}_${fbAuth.currentUser?.email}"
community 버튼을 클릭할 때마다 SimpleDateFormat()이 생성되기때문에, 불필요한 인스턴스가 늘어날 것 같네요.

2022-12-03 09:01 UTC, dktfr commented on frog/src/main/java/kr/co/ky/community/CommunityWriteActivity.kt
> +                    communityDataClass.timestamp = System.currentTimeMillis()
생성자의 파라미터로 넘기지 않고, 이렇게 작성하신 이유가 있을까요??

생성자의 파라미터로 넘기는 것과, 생성된 인스턴스에 프로퍼티를 넣는것의 차이점은 무엇일까요??

2022-12-03 09:01 UTC, dktfr commented on frog/src/main/java/kr/co/ky/community/CommunityDataClass.kt
> +                              var like : Map<String,Boolean> = HashMap()){
모든 프로퍼티가 var로 되어있는데, CommunityDataClass에서 프로퍼티가 변경될 일이 있나요??
가변 프로퍼티보다는 불변 프로퍼티(val)이 좋습니다.

2022-12-03 09:01 UTC, dktfr commented on frog/src/main/java/kr/co/ky/kozoltime/MainActivity.kt
> +            ActivityCompat.requestPermissions(this, arrayOf(Manifest.permission.READ_EXTERNAL_STORAGE),1)
MainActivity가 실행될 때마다 권한요청을 하도록 로직을 구성하는 방식은 좋은 흐름이 아닙니다.
권한이 있는지 확인하고, 권한이 없는 경우에만 요청하도록 바꿔주세요.

그리고, 유저는 권한을 수락할수도, 거부할수도 있습니다.
그 부분이 없는데, 그 동작도 작성해주세요.

2022-12-03 09:01 UTC, dktfr commented on frog/src/main/java/kr/co/ky/imageLoad/SendImage.kt
> +class SendImage {
클래스는 특정 객체/사물을 의미하기 떄문에, 이름은 명사로 시작하는 것이 관례입니다.

2022-12-03 09:27 UTC, hifrogie commented on frog/src/main/java/kr/co/ky/community/CommunityWriteActivity.kt
> +            val fileName = "${SimpleDateFormat("yyyymmdd_HHmm").format(Date())}_${fbAuth.currentUser?.email}"
아예 filename을 없앴습니다

2022-12-03 09:32 UTC, hifrogie commented on frog/src/main/java/kr/co/ky/community/CommunityWriteActivity.kt
> +                    communityDataClass.timestamp = System.currentTimeMillis()
인스턴스는 heap에 저장되니까 heap의 값들이 계속 바뀔거 같아요

2022-12-03 09:34 UTC, hifrogie commented on frog/src/main/java/kr/co/ky/community/CommunityDataClass.kt
> +                              var like : Map<String,Boolean> = HashMap()){
네 바꾸었습니다.

2022-12-03 10:54 UTC, hifrogie commented on frog/src/main/java/kr/co/ky/imageLoad/SendImage.kt
> +class SendImage {
바꿨습니다

2022-12-03 11:01 UTC, hifrogie commented on frog/src/main/java/kr/co/ky/community/CommunityDataClass.kt
> +                              var like : Map<String,Boolean> = HashMap()){
ComunityWriteActivity에서 ComunityDataClass를 사용하고 있어요! var로 해야 에러가 안떠요

2022-12-03 12:53 UTC, hifrogie commented on frog/src/main/java/kr/co/ky/kozoltime/MainActivity.kt
> +            ActivityCompat.requestPermissions(this, arrayOf(Manifest.permission.READ_EXTERNAL_STORAGE),1)
추가 했습니다.

2022-12-03 14:01 UTC, hifrogie commented on frog/src/main/java/kr/co/ky/community/CommunityWriteActivity.kt
> +            val fileName = "${SimpleDateFormat("yyyymmdd_HHmm").format(Date())}_${fbAuth.currentUser?.email}"
스토리지에 파일 이름이 달라야해서 다시 filename 만들었어요

2022-12-06 05:37 UTC, hifrogie commented on frog/src/main/java/kr/co/ky/community/CommunityWriteActivity.kt
> +            val fileName = "${SimpleDateFormat("yyyymmdd_HHmm").format(Date())}_${fbAuth.currentUser?.email}"
싱글톤으로 바꿨어요

2022-12-06 05:42 UTC, hifrogie commented on frog/src/main/java/kr/co/ky/community/CommunityWriteActivity.kt
> +            val fileName = "${SimpleDateFormat("yyyymmdd_HHmm").format(Date())}_${fbAuth.currentUser?.email}"
싱글톤에 넣어도 싱글톤 객체만 재사용 되지 않는 것이니까 싱글톤 안에 함수는 계속 인스턴스를 생성할 거 같은데 새로운 시간을 정의하려면 인스턴스 생성은 필수 아닐까요? 어제 사실 이해를 잘 못했어요

2022-12-06 05:42 UTC, hifrogie commented on frog/src/main/java/kr/co/ky/community/CommunityWriteActivity.kt
> +                    communityDataClass.timestamp = System.currentTimeMillis()
생성자 안에 넣었어요

2022-12-06 05:43 UTC, hifrogie commented on frog/src/main/java/kr/co/ky/community/CommunityDataClass.kt
> +                              var like : Map<String,Boolean> = HashMap()){
네 바꿨습니다.

2022-12-06 13:19 UTC, dktfr approved these changes

2022-12-07 02:37 UTC, merged