스피너를 구현했습니다.
f-lab-edu/kozolTime pull request #24
Opened 2022-12-09 04:26 UTC by hifrogie

스피너를 구현했습니다.

2022-12-09 10:32 UTC, dktfr requested changes

2022-12-09 10:32 UTC, dktfr commented on frog/src/main/java/kr/co/ky/community/CommunityAdapter.kt
> +    private val uid = FirebaseAuth.getInstance().currentUser?.uid
클래스를 접근하는 순간 결합도가 생기게 됩니다.
Firebase 클래스를 접근하는 부분을 Adapter와 분리하면 좋겠습니다.

2022-12-09 10:32 UTC, dktfr commented on frog/src/main/java/kr/co/ky/community/CommunityDataClass.kt
> +                              val timestamp : Any? = null,
Any를 사용하여 SingleDate로부터 받는 String 타입까지 같이 저장하려는 시도로 보이는데요.
이렇게 작성하면 나중에 timestamp 변수를 보고, 해당 타입과 값을 유추하기가 어려워지고 잘못된 사용으로 이어질 수 있습니다.

SingleDate로부터 받는 String 타입의 날짜표현과, timestampe는 성격이 다르다고 생각이 되기때문에
분리하는 것이 좋아보입니다. (SRP 원칙)

2022-12-09 10:32 UTC, dktfr commented on frog/src/main/java/kr/co/ky/detail/detailPage.kt
> +class detailPage : AppCompatActivity() {
클래스 이름 소문자로 시작하네요.

2022-12-09 10:32 UTC, dktfr commented on frog/src/main/java/kr/co/ky/kozoltime/WriteActivity.kt
> +                    requestPermissions(arrayOf(android.Manifest.permission.READ_EXTERNAL_STORAGE),
권한 요청을 하고있는데, 권한이 완료된 이후에는 어떤 콜백메서드가 호출될까요?
확인하고, 권한요청 이후의 동작도 코드 작성해주세요~

2022-12-10 03:50 UTC, hifrogie commented on frog/src/main/java/kr/co/ky/community/CommunityAdapter.kt
> +    private val uid = FirebaseAuth.getInstance().currentUser?.uid
클래스에 따로 빼서 uid를 정의 했어요
companion object를 붙였구요~
companion object가 없으면 클래스 끼리 또 결합도가 생길까봐 붙였어요

2022-12-10 03:53 UTC, hifrogie commented on frog/src/main/java/kr/co/ky/community/CommunityDataClass.kt
> +                              val timestamp : Any? = null,
timestamp 기능은 전혀 사용하고 있지 않아서
sigleDate만 남기고 timestamp를 singledate 로 바꿀게요
singledate의 return 타입도 string으로 바꿨어요~

2022-12-10 04:14 UTC, hifrogie commented on frog/src/main/java/kr/co/ky/detail/detailPage.kt
> +class detailPage : AppCompatActivity() {
바꿨어욥

2022-12-10 04:38 UTC, hifrogie commented on frog/src/main/java/kr/co/ky/kozoltime/WriteActivity.kt
> +                    requestPermissions(arrayOf(android.Manifest.permission.READ_EXTERNAL_STORAGE),
laucher.launch(intent) 코드를 넣었어요

2022-12-11 09:17 UTC, dktfr requested changes

2022-12-11 09:17 UTC, dktfr commented on frog/src/main/java/kr/co/ky/community/CommunityWriteActivity.kt
> +                    requestPermissions(arrayOf(android.Manifest.permission.READ_EXTERNAL_STORAGE), 1000)
requestPermissions() 메서드로 권한을 요청하면 onRequestPermissionResult() 콜백으로 권한의 승인여부 로직을 작성해 주는게 원칙입니다. [문서](https://developer.android.com/reference/android/app/Activity#requestPermissions(java.lang.String[],%20int))

혹은 최근에 Jetpack에서 권한요청을 위해 만들어진 방법을 이용해도 좋습니다. [문서](https://developer.android.com/training/permissions/requesting?hl=ko&authuser=1)

2022-12-14 11:46 UTC, dktfr approved these changes
코멘트 확인하고 수정후에, 머지해주세요.

2022-12-14 11:46 UTC, dktfr commented on frog/src/main/java/kr/co/ky/community/CommunityWriteActivity.kt
> +                    intent = Intent(Intent.ACTION_OPEN_DOCUMENT)
이 intent는 Activity 내의 setIntent()를 호출하는 효과라서, 버그발생의 여지가 있습니다.
변수를 선언하도록 변경해주세요.

2022-12-15 04:42 UTC, merged