검색 기능을 구현했어요.
f-lab-edu/kozolTime pull request #26
Opened 2022-12-16 04:54 UTC by hifrogie

파이어 베이스는 전체 검색기능이 없어요.
컬렉션의 데이터 목록중 한 가지 에서만 검색이 되어서 일단 그렇게만 내용을 검색하도록 해놨구요 스피너로 컬렉션을 고르도록 해놧어요

2022-12-16 13:01 UTC, dktfr requested changes
수고하셨습니다. 코멘트 확인부탁드립니다.

해당 코드는, 모든 데이터를 다 불러와서 `String.contains()` 메서드를 이용하여 필터링을 수행했는데,
이 로직의 경우, 데이터가 많아지면 어떻게 될까요??

Firestore에도 데이터를 선별(쿼리)할 수 있는 기능들이 있습니다.
https://firebase.google.com/docs/firestore/query-data/queries#kotlin+ktx

이 문서를 참고하여 수정해주세요.

2022-12-16 13:01 UTC, dktfr commented on frog/src/main/java/kr/co/ky/search/SearchActivity.kt
> +            binding.searchSpinner.adapter = adapter
binding.searchSpinner에 adapter를 중복해서 지정하고 있습니다.

2022-12-16 13:01 UTC, dktfr commented on frog/src/main/java/kr/co/ky/search/SearchActivity.kt
> +    lateinit var searchSpinner: String
searchSpinner라는 변수명이, 이 변수에 어떤 값이 저장되는지 모호합니다.
데이터가 의미하는 바를 알려주는 이름으로 바꾸면 좋겠습니다.

2022-12-16 13:01 UTC, dktfr commented on frog/src/main/java/kr/co/ky/search/SearchActivity.kt
> +                            if (snapshot.getString("context")!!
it.result와 snapshot.getString("context")가 null이 아니라는 확신이 있는 데이터일까요??
백엔드로부터 오는 값을 NotNull 처리하게되면, 백엔드에서 잘못된 데이터를 넘겨줄 때 앱에서 예외가 발생할 수도 있어서 주의가 필요합니다.

2022-12-19 04:00 UTC, hifrogie commented
contains()메소드를 사용하면 모든 데이터를 가져와서 처리해줍니다. 쿼리를 사용하면 데이터를 필요한만큼만 불러와서 처리를 해줍니다. contains()를 사용하면 불필요한 작업을 많이 해줘야할 것 같습니다.

2022-12-19 04:09 UTC, hifrogie commented on frog/src/main/java/kr/co/ky/search/SearchActivity.kt
> +            binding.searchSpinner.adapter = adapter
중복 없앴어요

2022-12-19 04:15 UTC, hifrogie commented on frog/src/main/java/kr/co/ky/search/SearchActivity.kt
> +    lateinit var searchSpinner: String
spinnerForSearch 라고 바꿨어요

2022-12-19 04:29 UTC, hifrogie commented on frog/src/main/java/kr/co/ky/search/SearchActivity.kt
> +                            if (snapshot.getString("context")!!
if (it.isSuccessful) 앞의 조건문이 널을 못들어오게 막아주는 역할을 하지 않나보네요 !!를 없앴습니다. 없어도 잘 되네요

2022-12-19 12:03 UTC, dktfr approved these changes

2022-12-20 07:33 UTC, merged