상세페이지와 채팅 기능 구현
f-lab-edu/kozolTime pull request #27
Opened 2022-12-22 05:38 UTC by hifrogie

카드 뷰를 누르면 상세페이지가 나오도록 구현했습니다.
하나의 adapter 안에서 여러 카테고리에 맞는 정보를 activity로 넘겨줘야 했습니다.

1. adapter 생성자를 통해 Fragment에서 가져온 카테고리 이름을 when 문에 넣고 카테고리 별로 처리하기
2. intent에 카테고리에 넘길 정보 담기
3. startActivity로 DetailActivity로 정보 넘기기

2022-12-22 10:42 UTC, dktfr requested changes

2022-12-22 10:42 UTC, dktfr commented on frog/src/main/AndroidManifest.xml
> +            android:launchMode="singleTop"/>
SingleTop 속성은 무엇인가요?
왜 Detail 화면에서 SingleTop 속성을 사용하셨나요?

2022-12-22 10:42 UTC, dktfr commented on frog/src/main/java/data/DetailFirebase.kt
> +                return@addSnapshotListener
이렇게 분기문에서 return을 해주어야 하는 경우, 가장 위에서 해주면 그다음에는 코드를 읽기에 수월해집니다.
 `early return 패턴`을 검색해보세요.

2022-12-22 10:42 UTC, dktfr commented on frog/src/main/java/kr/co/ky/detail/DetailAdapter.kt
> +    inner class ViewHolder(val binding: DetailCardviewBinding):RecyclerView.ViewHolder(binding.root){
inner 키워드를 붙인 이유는 무엇인가요?

2022-12-22 10:42 UTC, dktfr commented on frog/src/main/java/kr/co/ky/community/CommunityAdapter.kt
> +            when (collection) {
이 내용을 likeInterface처럼 어댑터 밖으로 빼면 좋겠습니다.
Adapter는 화면을 그려주는 역할만 하고, 특정 동작은 전부 Adapter의 외부에서 하도록 만들어주면 좋습니다.

2022-12-22 10:42 UTC, dktfr commented on frog/src/main/java/kr/co/ky/detail/DetailPage.kt
> +                FirebaseFirestore.getInstance().collection(page).document(documentFromAdapter)
이 동작은 Firebase를 다루는 동작인데, DetailFirebase 클래스의 내부로 넣으면 역할분리가 잘 되는 구조가 되겠네요.

2022-12-22 10:42 UTC, dktfr commented on frog/src/main/java/data/DetailListener.kt
> +    fun detail(mutableDetailList: MutableList<CommunityDataClass.Comment>)
detail() 함수 내부에서 데이터를 수정할 일이 없어야 할 것 같은데요.
굳이 Mutable 클래스로 타입을 지정한 이유가 있나요?

2022-12-23 08:11 UTC, hifrogie commented on frog/src/main/AndroidManifest.xml
> +            android:launchMode="singleTop"/>
detailpage에 intent를 보내고 싶은데 안되서 구글에 검색했더니 저걸 추가 하는 방법을 알려줬는데 의미 없는 거 같아요
삭제 하겠습니다.

2022-12-23 08:26 UTC, hifrogie commented on frog/src/main/java/data/DetailFirebase.kt
> +                return@addSnapshotListener
바꿨습니다~

2022-12-23 08:32 UTC, hifrogie commented on frog/src/main/java/kr/co/ky/detail/DetailAdapter.kt
> +    inner class ViewHolder(val binding: DetailCardviewBinding):RecyclerView.ViewHolder(binding.root){
참조중인 다른 변수가 없어서 inner 키워드 지웠어요

2022-12-23 09:36 UTC, hifrogie commented on frog/src/main/java/kr/co/ky/community/CommunityAdapter.kt
> +            when (collection) {
바꾸었어요~

2022-12-23 09:57 UTC, hifrogie commented on frog/src/main/java/kr/co/ky/detail/DetailPage.kt
> +                FirebaseFirestore.getInstance().collection(page).document(documentFromAdapter)
detailFirebase에 넣었어요~

2022-12-23 09:58 UTC, hifrogie commented on frog/src/main/java/data/DetailListener.kt
> +    fun detail(mutableDetailList: MutableList<CommunityDataClass.Comment>)
댓글을 수정할 때를 대비해서 넣었어요

2022-12-23 12:06 UTC, dktfr commented on frog/src/main/AndroidManifest.xml
> +            android:launchMode="singleTop"/>
네, 저 속성이 무엇인지 공부해서 코멘트로 남겨주세요~

2022-12-24 01:03 UTC, dktfr requested changes
코멘트 확인부탁드립니다

2022-12-24 01:03 UTC, dktfr commented on frog/src/main/java/data/DetailFirebase.kt
> +    fun sendDetailFirebase(editText:String?,page:String,documentFromAdapter:String){
변수명 신경써서 짓는 습관을 들여주세요

2022-12-24 01:03 UTC, dktfr commented on frog/src/main/java/kr/co/ky/cardviewCollection/CardviewCollection.kt
> +    lateinit var intent : Intent
클래스의 한 부분에서만 사용되기때문에, 메서드 내의 지역변수로 바꾸는게 좋겠습니다.

2022-12-24 01:03 UTC, dktfr commented on frog/src/main/java/navigation/MyPage.kt
> +        var nickname:String? = null
sendDetailFirebase() 메서드 내부에서 사용하기 위해서 companion object를 사용하고 있는데,
이렇게 데이터를 공유하는 방식은 좋지 않습니다.
안드로이드에서는 Fragment간 데이터를 공유하기 위한 방법으로 ViewModel을 권장하고 있습니다.
ViewModel을 공부해서 사용하도록 바꿔주세요
https://developer.android.com/topic/libraries/architecture/viewmodel?hl=ko

2022-12-24 01:03 UTC, dktfr commented on frog/src/main/java/data/DetailFirebase.kt
> +            nickname = MyPage.nickname,
이 방식은 DetailFirebase가 MyPage 클래스를 참조하게 되므로 좋지 않습니다.
nickname을 메서드의 인자로 받도록 바꿔주세요.

2022-12-26 02:07 UTC, hifrogie commented on frog/src/main/AndroidManifest.xml
> +            android:launchMode="singleTop"/>
singleTop은 액티비티의 인스턴스가 이미 대상 작업의 맨 위에 존재하는 경우 시스템은 새 액티비티를 생성하는 대신 onNewIntent()메서드를 호출하여 인스턴스로 라우팅합니다.

2022-12-30 12:48 UTC, dktfr requested changes

2022-12-30 12:48 UTC, dktfr commented on frog/src/main/java/kr/co/ky/detail/DetailPage.kt
> +                    DetailFirebase().setDetailview(binding.detailPageChatEditText.text.toString(),
DetailFirebase의 인스턴스를 엑티비티의 프로퍼티로 지정해두면, 매번 생성하지 않아도 될 것 같은데요
혹시 인스턴스를 매번 생성하는 이유가 있으신가요?

2022-12-30 12:48 UTC, dktfr commented on frog/src/main/java/kr/co/ky/kozoltime/MainActivity.kt
> +        private lateinit var viewModel: NicknameViewModel
MainActivity에서 사용되지 않으므로, 삭제해도 될 것 같네요

2022-12-30 12:48 UTC, dktfr commented on frog/src/main/java/kr/co/ky/nicknamePackage/NickAsync.kt
> +class NickAsync {
코루틴을 잘 이해하고 작성하신 코드일까요?
기왕 사용하셨으니까, 다음 멘토링시간에 코루틴에 대해서 질문할 예정입니다.
공부해와주세요.

2022-12-30 12:48 UTC, dktfr commented on frog/src/main/java/kr/co/ky/nicknamePackage/NickDataClass.kt
> +class NickDataClass ( val nickname:String? = null
data 클래스가 아니라 일반클래스로 선언한 이유가 있으신가요?

2022-12-30 12:48 UTC, dktfr commented on frog/src/main/java/kr/co/ky/nicknamePackage/NicknameViewModel.kt
> +                NickFirebase().sendNickFirebase(object : NickCallback {
지금 이 코드는 getNick()이 호출될 때마다 NickFirebase의 인스턴스를 생성하게 되는데요.
이렇게 짠 이유가 있으실까요?

2022-12-30 12:48 UTC, dktfr commented on frog/src/main/java/navigation/MyPage.kt
> +                    viewModel.nickState.observe(viewLifecycleOwner, Observer {
들여쓰기 신경써주세요. 코드의 가독성이 좋지않습니다ㅠㅠ

2022-12-31 01:51 UTC, dktfr approved these changes
ViewModel, LiveData에 대해 아직 수정해야 할 부분이 있지만, 일단 approve 합니다.
다음 멘토링시간 이후에, 리팩토링 과제로 수정해보면 좋겠습니다.

2022-12-31 02:51 UTC, merged