구글 로그인 구현했어요
f-lab-edu/kozolTime pull request #5
Opened 2022-11-03 10:26 UTC by hifrogie

페이스북은 아이디를 옛날에 삭제 해서 다시 아이디를 복구하려면 하루정도 시간이 걸려서 내일 하려구요

2022-11-03 11:37 UTC, dktfr requested changes
전체적으로 코드의 정렬이 어긋나있고, 불필요한 주석이 많습니다.
변수나 함수의 이름을 명확하게 지어주면, 주석이 없어도 코드를 이해하기 쉬워집니다.

2022-11-03 11:37 UTC, dktfr commented on frog/src/main/java/kr/co/ky/kozoltime/LoginActivity.kt
> +    var GOOGLE_LOGIN_CODE = 9001
LOGIN_CODE가 다른곳에서 값이 바뀌지 않을텐데 var로 선언하신 이유가 있나요?
다른 개발자와 함께 작업할 때, 코드를 모르는 개발자가 중간에 어떤 메서드에서 함부로 GOOGLE_LOGIN_CODE의 값을 변경하면 어떻게 될까요?

그리고 해당 CODE는 아래에서 사용되고 있지 않습니다.

2022-11-03 11:37 UTC, dktfr commented on frog/src/main/java/kr/co/ky/kozoltime/LoginActivity.kt
> +        auth = FirebaseAuth.getInstance()
FirebaseAuth 인스턴스는 엑티비티의 라이프사이클과 무관한데, onCreate에서 초기화한 이유가 있을까요?

2022-11-03 11:37 UTC, dktfr commented on frog/src/main/java/kr/co/ky/kozoltime/LoginActivity.kt
> +            if(user != null){
user가 null일때의 방어코드도 추가되어야 할 것 같습니다.

2022-11-03 11:37 UTC, dktfr commented on frog/src/main/java/kr/co/ky/kozoltime/LoginActivity.kt
> +       registerForActivityResult(ActivityResultContracts.StartActivityForResult()){
왜 구글에서는 `onActivityResult()` 콜백함수를 Deprecate하고 이 방식으로 바꾸었을까요?

2022-11-04 07:27 UTC, hifrogie commented on frog/src/main/java/kr/co/ky/kozoltime/LoginActivity.kt
> +    var GOOGLE_LOGIN_CODE = 9001
동영상을 보면서 따라하다가 LOGIN_CODE를 쓰는 함수가 deprecated 되어서 다른 것으로 대체하다보니 LOGIN_CODE를 안 쓰게 되었네요 삭제 하겠습니다.
값을 변경하면 앱은 LOGIN_CODE를 쓰고 있지 않아서 아무런 변화가 없을 것 같습니다.

2022-11-04 07:29 UTC, hifrogie commented on frog/src/main/java/kr/co/ky/kozoltime/LoginActivity.kt
> +        auth = FirebaseAuth.getInstance()
signinAndSignUp 함수에서 사용하기 위해서 입니다.

2022-11-05 03:41 UTC, dktfr commented on frog/src/main/java/kr/co/ky/kozoltime/LoginActivity.kt
> +    var GOOGLE_LOGIN_CODE = 9001
현재로써는 LOGIN_CODE를 쓰고있지 않아서 아무런 변화가 없었겠지만,
만약 사용하고있었다면 버그유발의 소지가 발생합니다.

변경가능성을 잘 생각해서 val / var를 적절하게 사용해주세요~

2022-11-05 03:41 UTC, dktfr commented on frog/src/main/java/kr/co/ky/kozoltime/LoginActivity.kt
> +        auth = FirebaseAuth.getInstance()
onCreate대신 멤버변수 선언부에서 초기화해도 되지 않았을까요??

2022-11-08 12:35 UTC, hifrogie commented on frog/src/main/java/kr/co/ky/kozoltime/LoginActivity.kt
> +    var GOOGLE_LOGIN_CODE = 9001
넵 아예 지웠어요!

2022-11-08 12:45 UTC, hifrogie commented on frog/src/main/java/kr/co/ky/kozoltime/LoginActivity.kt
> +        auth = FirebaseAuth.getInstance()
네 그렇게 바꿨습니다.

2022-11-08 12:46 UTC, hifrogie commented on frog/src/main/java/kr/co/ky/kozoltime/LoginActivity.kt
> +            if(user != null){
추가 했습니다.

2022-11-08 12:47 UTC, hifrogie commented on frog/src/main/java/kr/co/ky/kozoltime/LoginActivity.kt
> +       registerForActivityResult(ActivityResultContracts.StartActivityForResult()){
코드가 길어지고 퍼미션 요청이 힘들기 때문입니다.

2022-11-09 09:38 UTC, closed without merging