로그인을 하면 새로운 아이디만 로그인 되서 다시 브랜치를 만들었어요
f-lab-edu/kozolTime pull request #6
Opened 2022-11-04 11:07 UTC by hifrogie

새로운 아이디만 로그인 되는 문제와 회원가입 버튼이 없고 새로운 아이디는 무조건 가입되는 문제를 해결했습니다.
그냥 브랜치를 수정하면 됐는데 실수로 브랜치를 또 만들어 버렸어요 죄송합니다.

2022-11-05 03:39 UTC, dktfr requested changes

2022-11-05 03:39 UTC, dktfr commented on frog/.gitignore
> +LoginActivity.kt
.gitignore에서 제외되면 안되는 파일들도 제외가 되었네요.
지금 이대로 다른사람이 레포지토리를 받아서 빌드하려고하면 빌드되지 않을꺼에요.

android project 구조에 대해서 다시 공부하시고, gitignore를 수정해주세요~
https://developer.android.com/studio/projects
https://curryyou.tistory.com/366
https://youngest-programming.tistory.com/180

2022-11-05 03:39 UTC, dktfr commented on frog/build.gradle
> +        targetCompatibility 1.8
똑같은 속성을 또 추가하신 이유는 무엇일까요??

2022-11-05 03:39 UTC, dktfr commented on frog/src/main/java/navigation/communityFragment.kt
> +class communityFragment : Fragment(){
클래스 이름은 대문자로 시작하는것이 개발자들 사이의 약속입니다~

2022-11-05 03:39 UTC, dktfr commented on frog/src/main/res/layout/activity_login_join.xml
> +        android:hint="아이디 입력 "
문자열 리소스 사용을 습관화해주세요.

2022-11-05 03:39 UTC, dktfr commented on frog/src/main/res/layout/activity_main.xml
> +            >
코드 여백, 스타일에 신경써 주세요.
지금부터 코드를 깔끔하게 짜고 정리하는 습관을 들여야, 실무에서도 그대로 하게 됩니다.
나중에 고쳐야지 라고 생각하면 잘 안고쳐져요^^;;

2022-11-05 03:39 UTC, dktfr commented on frog/src/main/res/values/strings.xml
> +    <item name="masked" type="id" />
어디에 쓰이는 값인가요?

2022-11-05 07:27 UTC, hifrogie commented on frog/.gitignore
> +LoginActivity.kt
수정했어요~

2022-11-05 07:27 UTC, hifrogie commented on frog/build.gradle
> +        targetCompatibility 1.8
dependency 추가하다가 실수로 추가했어요

2022-11-05 07:29 UTC, hifrogie commented on frog/src/main/java/navigation/communityFragment.kt
> +class communityFragment : Fragment(){
네~

2022-11-05 07:29 UTC, hifrogie commented on frog/src/main/res/layout/activity_login_join.xml
> +        android:hint="아이디 입력 "
넵

2022-11-05 07:49 UTC, hifrogie commented on frog/src/main/res/layout/activity_main.xml
> +            >
네 신경써서 하겠습니다.

2022-11-05 07:50 UTC, hifrogie commented on frog/src/main/res/values/strings.xml
> +    <item name="masked" type="id" />
동영상 강의에서 복붙한건데 아직 수업에 안나와서 모르겠어요 ㅜㅜ

2022-11-07 14:04 UTC, hifrogie commented on frog/build.gradle
> +        targetCompatibility 1.8
중복 된거 삭제 했어요~

2022-11-07 14:04 UTC, hifrogie commented on frog/src/main/java/navigation/communityFragment.kt
> +class communityFragment : Fragment(){
고쳤어요~

2022-11-07 15:01 UTC, hifrogie commented on frog/src/main/res/layout/activity_main.xml
> +            >
고쳤어요~

2022-11-08 12:49 UTC, hifrogie commented
두번쨰 풀리퀘에서 조언해 주신 내용 적용해서 커밋했어요 
두번째 풀리퀘에 해당하는 브랜치는 삭제하겠습니다!

2022-11-08 23:18 UTC, dktfr approved these changes
고생하셨습니다!

2022-11-09 09:37 UTC, merged